import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TailWindCard from './TailWindCard'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JoMedeiros CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='bg-black text-white font-sans mx-0 rounded-b-lg'>
        <nav className='p-4'>
          <ul className='flex'>
            <li className='px-4'><a href="/">Página inicial</a></li>
            <li className='px-4 font-bold'><a href="/curriculum">Curriculum</a></li>
          </ul>
        </nav>
      </header>

      <main className={styles.main + ' p-0'}>
        {/* <TailWindCard /> */}

        <section className="w-[36rem] bg-black shadow shadow-black/90 p-4 rounded my-4 text-white">
          <h1 className="text-xl font-bold underline">Links</h1>
          <br />
          <p>
            Github: <a className='underline' href="https://github.com/jomedeiros">https://github.com/jomedeiros</a>
          </p>
          <p>
            LinkedIn: <a className='underline' href="https://www.linkedin.com/in/josivan-medeiros-10950a83/">https://www.linkedin.com/in/josivan-medeiros-10950a83/</a>
          </p>
        </section>

        <section className='w-[36rem] shadow shadow-black/90 p-4 rounded bg-black text-white'>
          <h1 className='text-xl font-bold underline'>Habilidades</h1>
          <br />
          <p>Gerais: Git, PostgreSQL, HTML, CSS, bash.</p>
          <p>Bibliotecas python: Matplotlib, Numpy, Pandas, SKLearn e OpenCV.</p>
          <p>Frameworks Java: Spring.</p>
        </section>

        <section className="w-[36rem] bg-black shadow shadow-black/90 p-4 rounded my-4 text-white">
          <h1 className='text-xl font-bold underline'>Experiência</h1>
          <br />
          <div className="flex items-baseline mt-4 mb-6 pb-6 border-b border-slate-400">
            <div className="space-x-2 flex text-sm">
              <div className="flex flex-wrap">
                <h1 className="flex-auto text-lg font-semibold text-slate-200">
                  PET de Ciência da Computação (UFRN)
                </h1>
                <div className="text-lg font-semibold text-slate-400">
                  Bolsista
                </div>
                <div className="w-full flex-none text-sm font-medium text-slate-400 mt-2">
                  2017 - 2021
                </div>
                <p>Dar tutorial das disciplinas do curso de Ciência da Computação, dar apoio a Eventos, elaborar e ministrar cursos de férias e de verão, fazer seminários de pesquisas relacionados a área de interesse do bolsista.</p>
                <p>Cursos Ministrados:</p>
                <ul className='list-disc list-inside' role='list'>
                  <br />
                  <li>Desenvolvimento Mobile com Ionic.</li>
                  <li>Programação Orientada a Objeto (C/C++).</li>
                  <li>Latex</li>
                  <li>Introdução à Visão Computacional Utilizando OpenCV.</li>
                  <li>Aprendizado de Máquina com Python.</li>
                  <li>Programação Orientada a Objeto (Java).</li>
                  <li>Jogos 2D com Unity.</li>
                  <li>Shellscript Linux (para o XIV EAMC do LNCC).</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="flex items-baseline mt-4 mb-6 pb-6 border-b border-slate-400">
            <div className="flex flex-wrap">
              <h1 className="flex-auto text-lg font-semibold text-slate-200">
                CTINF - SEED/RN
              </h1>
              <div className="text-lg font-semibold text-slate-400">
                Estagiário
              </div>
              <div className="w-full flex-none text-sm font-medium text-slate-400 mt-2">
                Abril - Junho de 2021
              </div>
              <p>Desenvolvimento Fullstack em Java com framework Spring e template engine Thymeleaf.</p>
            </div>
          </div>

          <div className="flex flex-wrap">
            <h1 className="flex-auto text-lg font-semibold text-slate-200">
              ESIG Software & Consultoria
            </h1>
            <div className="text-lg font-semibold text-slate-400">
              Analista Desenvolvedor
            </div>
            <div className="w-full flex-none text-sm font-medium text-slate-400 mt-2">
              Agost de 2021 - Atual
            </div>
            <p>Desenvolvimeto Fullstack em Java com JSF e JPA. Manutenção do sistema Sigeduc, um sistema de gestão escolar.</p>
          </div>
          <br />

        </section>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/JoMedeiros"
          target="_blank"
          rel="noopener noreferrer"
        >
          feito por Josivan Gois - 2022
        </a>
      </footer>
    </div>
  )
}
