import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import TailWindCard from './TailWindCard'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Página Inicial - JoMedeiros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='bg-black text-white font-sans mx-0 rounded-b-lg shadow shadow-black/50'>
        <nav className='p-4'>
          <ul className='flex'>
            <li className='px-4 font-bold'>
              <Link href="/"><a>Página inicial</a></Link>
            </li>
            <li className='px-4'>
              <Link href="/curriculum"><a>Curriculum</a></Link>
            </li>
          </ul>
        </nav>
      </header>

      <main className={styles.main}>
        <TailWindCard/>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/JoMedeiros"
          target="_blank"
          rel="noopener noreferrer"
        >
          feito por Josivan Gois - 2022
        </a>
      </footer>
    </div>
  )
}
